### ISSUE TITLE
This is not ruby.  There are no "gems". and so on.. 

### ISSUE THREAD

**Issue by nkuehn** [iron-io/iron_worker_node#23]
This module and also the overall documentation for node seems to be written and documented by ruby devs that have not really tried to get into the node wording, ecosystem etc. 

the README is talking about "gems", the documentation ( http://dev.iron.io/worker/languages/nodejs/ ) is full of ruby fragments, ruby terminologies and links into ruby sourcecode. 

Ruby is not Node.  In the first moment it's confusing (I though I have to install the ruby CLI to be able to use the node module), then disappointing because Node is in fact an extremely suited runtime for iron workers (and cheap for iron because of low mem and startup CPU requirements) and it feels like a copy / paste stepchild.

**Comment by pulkitsinghal** [comment]
Hello @nkuehn, I too have been using IronWorkers for a long time and I'm surprised you found that page at all! It had recently (year ago?) disappeared. I had not bookmarked it and the updated navigation only led me to the latest CLI tool: http://dev.iron.io/worker/cli/

I personally thought they had taken that page down altogether but as you point out it is still around and still somehow discoverable and confusing. They can probably take it down unless there is a very specific reason they've left it for legacy customers.

Is there anything I can help you specifically with as a fellow community member? Other than the big "plus one" that I slapped onto your post?

**Comment by antony** [comment]
FWIW the Node client isn't node either. I'm not sure what the 'home language' of any of Iron's devs is, but it's confusing trying to use libraries which don't conform to basics of the intended ecosystem.

I think the best approach is to raise issues for each individual problem and gradually they can be fixed - that or use a non-official client.
