### ISSUE TITLE
Add support for /clusters endpoint?

### ISSUE THREAD

**Issue by mattdiamond** [iron-io/iron_worker_node#26]
I've noticed that this library does not support the /clusters endpoint exposed by the IronWorkers API. Any plans to include this in a future version?

**Comment by alex-litvak** [comment]
@mattdiamond Thanks for the good question. This endpoint was added for [hybrid](http://kb.iron.io/ironworker/advanced-configuration/hybrid-deployment-get-started) IronWorker clusters. We will include this in the future version of iron_worker_node and other IronWorker client libs.

**Comment by alex-litvak** [comment]
Added in https://github.com/iron-io/iron_worker_node/pull/27
